language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install nose-exclude"
  - "pip install -r requirements.txt"
  - "pip install pytest"
  - "pip install coveralls"
  - "pip install -e ."
script: 
  - nosetests --exclude-dir=generator
  - coverage run --source=pyidf --omit='*/generator/*,*/tests/*'
after_success:
  - coveralls
